Automic/Index

- pck.automic_aratools.index
PCK.AUTOMIC_ARATOOLS-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_ARATOOLS-1.0.0

- pck.automic_cvs.index
PCK.AUTOMIC_CVS-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_CVS-1.0.0

- pck.automic_email.index
PCK.AUTOMIC_EMAIL-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_EMAIL-1.0.0

- pck.automic_filesystem.index
PCK.AUTOMIC_FILESYSTEM-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_FILESYSTEM-1.0.0

- pck.automic_agent_2_agent.index
PCK.AUTOMIC_AGENT_2_AGENT-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_AGENT_2_AGENT-1.0.0

- pck.automic_ftp.index
PCK.AUTOMIC_FTP-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_FTP-1.0.0

- pck.automic_xml.index
PCK.AUTOMIC_XML-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_XML-1.0.0

- pck.automic_http.index
PCK.AUTOMIC_HTTP-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_HTTP-1.0.0

- pck.automic_windows_service.index
PCK.AUTOMIC_WINDOWS_SERVICE-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_WINDOWS_SERVICE-1.0.0

- pck.automic_windows_registry.index
PCK.AUTOMIC_WINDOWS_REGISTRY-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_WINDOWS_REGISTRY-1.0.0

- pck.automic_ini.index
PCK.AUTOMIC_INI-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_INI-1.0.0

- pck.automic_windows.index
PCK.AUTOMIC_WINDOWS-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_WINDOWS-1.0.0

- pck.automic_unix.index
PCK.AUTOMIC_UNIX-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_UNIX-1.0.0

- pck.automic_tfs.index
PCK.AUTOMIC_TFS-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_TFS-1.0.0

- pck.automic_text.index
PCK.AUTOMIC_TEXT-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_TEXT-1.0.0

- pck.itpa_shared.index
PCK.ITPA_SHARED-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.ITPA_SHARED-1.0.0

- pck.automic_smb.index
PCK.AUTOMIC_SMB-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_SMB-1.0.0

- pck.automic_java_properties.index
PCK.AUTOMIC_JAVA_PROPERTIES-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_JAVA_PROPERTIES-1.0.0

- pck.automic_sftp.index
PCK.AUTOMIC_SFTP-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_SFTP-1.0.0

- pck.automic_scp.index
PCK.AUTOMIC_SCP-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_SCP-1.0.0

- pck.automic_svn.index
PCK.AUTOMIC_SVN-1.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_SVN-1.0.0

- pck.automic_database.index
PCK.AUTOMIC_DATABASE-1.1.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_DATABASE-1.1.0

- pck.automic_siebel.index
PCK.AUTOMIC_SIEBEL-2.0.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_SIEBEL-2.0.0

- pck.automic_shared.index
PCK.AUTOMIC_SHARED-1.1.0 is here. Please merge!
> stephanschratzberger:PCK.AUTOMIC_SHARED-1.1.0

- pck.automic_agent_2_agent.index
pck.automic_agent_2_agent-1.0.0 is here. Please merge!
> automic-infra:pck.automic_agent_2_agent-1.0.0

- pck.automic_aratools.index
pck.automic_aratools-1.0.0 is here. Please merge!
> automic-infra:pck.automic_aratools-1.0.0

- pck.automic_cvs.index
pck.automic_cvs-1.0.0 is here. Please merge!
> automic-infra:pck.automic_cvs-1.0.0

- pck.automic_email.index
pck.automic_email-1.0.0 is here. Please merge!
> automic-infra:pck.automic_email-1.0.0

- pck.automic_ftp.index
pck.automic_ftp-1.0.0 is here. Please merge!
> automic-infra:pck.automic_ftp-1.0.0

- pck.automic_filesystem.index
pck.automic_filesystem-1.0.0 is here. Please merge!
> automic-infra:pck.automic_filesystem-1.0.0

- pck.automic_http.index
pck.automic_http-1.0.0 is here. Please merge!
> automic-infra:pck.automic_http-1.0.0

- pck.automic_ini.index
pck.automic_ini-1.0.0 is here. Please merge!
> automic-infra:pck.automic_ini-1.0.0

- pck.itpa_shared.index
pck.itpa_shared-1.0.0 is here. Please merge!
> automic-infra:pck.itpa_shared-1.0.0

- pck.automic_java_properties.index
pck.automic_java_properties-1.0.0 is here. Please merge!
> automic-infra:pck.automic_java_properties-1.0.0

- pck.automic_scp.index
pck.automic_scp-1.0.0 is here. Please merge!
> automic-infra:pck.automic_scp-1.0.0

- pck.automic_sftp.index
pck.automic_sftp-1.0.0 is here. Please merge!
> automic-infra:pck.automic_sftp-1.0.0

- pck.automic_smb.index
pck.automic_smb-1.0.0 is here. Please merge!
> automic-infra:pck.automic_smb-1.0.0

- pck.automic_svn.index
pck.automic_svn-1.0.0 is here. Please merge!
> automic-infra:pck.automic_svn-1.0.0

- pck.automic_tfs.index
pck.automic_tfs-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tfs-1.0.0

- pck.automic_text.index
pck.automic_text-1.0.0 is here. Please merge!
> automic-infra:pck.automic_text-1.0.0

- pck.automic_unix.index
pck.automic_unix-1.0.0 is here. Please merge!
> automic-infra:pck.automic_unix-1.0.0

- pck.automic_windows.index
pck.automic_windows-1.0.0 is here. Please merge!
> automic-infra:pck.automic_windows-1.0.0

- pck.automic_windows_registry.index
pck.automic_windows_registry-1.0.0 is here. Please merge!
> automic-infra:pck.automic_windows_registry-1.0.0

- pck.automic_windows_service.index
pck.automic_windows_service-1.0.0 is here. Please merge!
> automic-infra:pck.automic_windows_service-1.0.0

- pck.automic_xml.index
pck.automic_xml-1.0.0 is here. Please merge!
> automic-infra:pck.automic_xml-1.0.0

- pck.automic_hpqc.index
pck.automic_hpqc-1.0.0 is here. Please merge!
> automic-infra:pck.automic_hpqc-1.0.0

- pck.automic_docker.index
pck.automic_docker-1.0.0 is here. Please merge!
> automic-infra:pck.automic_docker-1.0.0

- pck.automic_database.index
pck.automic_database-1.1.0 is here. Please merge!
> automic-infra:pck.automic_database-1.1.0

- pck.automic_siebel.index
pck.automic_siebel-2.0.0 is here. Please merge!
> automic-infra:pck.automic_siebel-2.0.0

- pck.automic_shared.index
pck.automic_shared-1.0.0 is here. Please merge!
> automic-infra:pck.automic_shared-1.0.0

- pck.automic_aix.index
pck.automic_aix-1.0.0 is here. Please merge!
> automic-infra:pck.automic_aix-1.0.0

- pck.automic_agent_2_agent.index
pck.automic_agent_2_agent-1.1.0 is here. Please merge!
> automic-infra:pck.automic_agent_2_agent-1.1.0

- pck.automic_bond.index
pck.automic_bond-1.0.0 is here. Please merge!
> automic-infra:pck.automic_bond-1.0.0

- pck.automic_cvs.index
pck.automic_cvs-1.1.0 is here. Please merge!
> automic-infra:pck.automic_cvs-1.1.0

- pck.automic_connectivity.index
pck.automic_connectivity-1.0.0 is here. Please merge!
> automic-infra:pck.automic_connectivity-1.0.0

- pck.automic_deb.index
pck.automic_deb-1.0.0 is here. Please merge!
> automic-infra:pck.automic_deb-1.0.0

- pck.automic_dm.index
pck.automic_dm-1.0.0 is here. Please merge!
> automic-infra:pck.automic_dm-1.0.0

- pck.automic_email.index
pck.automic_email-1.1.0 is here. Please merge!
> automic-infra:pck.automic_email-1.1.0

- pck.automic_ftp.index
pck.automic_ftp-1.1.0 is here. Please merge!
> automic-infra:pck.automic_ftp-1.1.0

- pck.automic_filesystem.index
pck.automic_filesystem-1.1.0 is here. Please merge!
> automic-infra:pck.automic_filesystem-1.1.0

- pck.automic_hpux.index
pck.automic_hpux-1.0.0 is here. Please merge!
> automic-infra:pck.automic_hpux-1.0.0

- pck.automic_http.index
pck.automic_http-1.1.0 is here. Please merge!
> automic-infra:pck.automic_http-1.1.0

- pck.automic_ibm_websphere.index
pck.automic_ibm_websphere-1.0.0 is here. Please merge!
> automic-infra:pck.automic_ibm_websphere-1.0.0

- pck.automic_iis.index
pck.automic_iis-1.0.0 is here. Please merge!
> automic-infra:pck.automic_iis-1.0.0

- pck.automic_ini.index
pck.automic_ini-1.1.0 is here. Please merge!
> automic-infra:pck.automic_ini-1.1.0

- pck.itpa_shared.index
pck.itpa_shared-1.1.0 is here. Please merge!
> automic-infra:pck.itpa_shared-1.1.0

- pck.automic_jboss_v6.index
pck.automic_jboss_v6-1.0.0 is here. Please merge!
> automic-infra:pck.automic_jboss_v6-1.0.0

- pck.automic_jdbc.index
pck.automic_jdbc-1.0.0 is here. Please merge!
> automic-infra:pck.automic_jdbc-1.0.0

- pck.automic_java_properties.index
pck.automic_java_properties-1.1.0 is here. Please merge!
> automic-infra:pck.automic_java_properties-1.1.0

- pck.automic_ldap.index
pck.automic_ldap-1.0.0 is here. Please merge!
> automic-infra:pck.automic_ldap-1.0.0

- pck.automic_log.index
pck.automic_log-1.0.0 is here. Please merge!
> automic-infra:pck.automic_log-1.0.0

- pck.automic_msi.index
pck.automic_msi-1.0.0 is here. Please merge!
> automic-infra:pck.automic_msi-1.0.0

- pck.automic_rpm.index
pck.automic_rpm-1.0.0 is here. Please merge!
> automic-infra:pck.automic_rpm-1.0.0

- pck.automic_scp.index
pck.automic_scp-1.1.0 is here. Please merge!
> automic-infra:pck.automic_scp-1.1.0

- pck.automic_sftp.index
pck.automic_sftp-1.1.0 is here. Please merge!
> automic-infra:pck.automic_sftp-1.1.0

- pck.automic_smb.index
pck.automic_smb-1.1.0 is here. Please merge!
> automic-infra:pck.automic_smb-1.1.0

- pck.automic_svn.index
pck.automic_svn-1.1.0 is here. Please merge!
> automic-infra:pck.automic_svn-1.1.0

- pck.automic_tfs.index
pck.automic_tfs-1.1.0 is here. Please merge!
> automic-infra:pck.automic_tfs-1.1.0

- pck.automic_text.index
pck.automic_text-1.1.0 is here. Please merge!
> automic-infra:pck.automic_text-1.1.0

- pck.automic_tomcat.index
pck.automic_tomcat-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tomcat-1.0.0

- pck.automic_unix.index
pck.automic_unix-1.1.0 is here. Please merge!
> automic-infra:pck.automic_unix-1.1.0

- pck.automic_windows_registry.index
pck.automic_windows_registry-1.1.0 is here. Please merge!
> automic-infra:pck.automic_windows_registry-1.1.0

- pck.automic_windows_service.index
pck.automic_windows_service-1.1.0 is here. Please merge!
> automic-infra:pck.automic_windows_service-1.1.0

- pck.automic_windows.index
pck.automic_windows-1.1.0 is here. Please merge!
> automic-infra:pck.automic_windows-1.1.0

- pck.automic_xml.index
pck.automic_xml-1.1.0 is here. Please merge!
> automic-infra:pck.automic_xml-1.1.0

- pck.automic_excel.index
pck.automic_excel-1.0.0 is here. Please merge!
> automic-infra:pck.automic_excel-1.0.0

- pck.automic_siebel.index
pck.automic_siebel-3.0.0 is here. Please merge!
> automic-infra:pck.automic_siebel-3.0.0

- pck.automic_vss.index
pck.automic_vss-1.0.0 is here. Please merge!
> automic-infra:pck.automic_vss-1.0.0

- pck.automic_azure.index
pck.automic_azure-1.0.0 is here. Please merge!
> automic-infra:pck.automic_azure-1.0.0

- pck.automic_docker.index
pck.automic_docker-1.1.0 is here. Please merge!
> automic-infra:pck.automic_docker-1.1.0

- pck.automic_azure.index
pck.automic_azure-1.0.1 is here. Please merge!
> automic-infra:pck.automic_azure-1.0.1

- pck.automic_azure.index
pck.automic_azure-1.0.2 is here. Please merge!
> automic-infra:pck.automic_azure-1.0.2

- pck.automic_openstack.index
pck.automic_openstack-1.0.0 is here. Please merge!
> automic-infra:pck.automic_openstack-1.0.0

- pck.automic_ansible.index
pck.automic_ansible-1.0.0 is here. Please merge!
> automic-infra:pck.automic_ansible-1.0.0

- pck.automic_smoke_web.index
pck.automic_smoke_web-1.0.0 is here. Please merge!
> automic-infra:pck.automic_smoke_web-1.0.0

- pck.automic_f5_bigip.index
pck.automic_f5_bigip-1.0.0 is here. Please merge!
> automic-infra:pck.automic_f5_bigip-1.0.0

- pck.automic_solaris.index
pck.automic_solaris-1.0.0 is here. Please merge!
> automic-infra:pck.automic_solaris-1.0.0

- pck.automic_docker.index
pck.automic_docker-1.2.0 is here. Please merge!
> automic-infra:pck.automic_docker-1.2.0

- pck.automic_hpqc.index
pck.automic_hpqc-1.1.0 is here. Please merge!
> automic-infra:pck.automic_hpqc-1.1.0

- pck.automic_jenkins.index
pck.automic_jenkins-1.0.0 is here. Please merge!
> automic-infra:pck.automic_jenkins-1.0.0

- pck.automic_weblogic.index
pck.automic_weblogic-1.0.0 is here. Please merge!
> automic-infra:pck.automic_weblogic-1.0.0

- pck.automic_tomcat.index
pck.automic_tomcat-1.0.1 is here. Please merge!
> automic-infra:pck.automic_tomcat-1.0.1

- pck.automic_jdbc.index
pck.automic_jdbc-1.1.0 is here. Please merge!
> automic-infra:pck.automic_jdbc-1.1.0

- pck.automic_chef.index
pck.automic_chef-1.0.0 is here. Please merge!
> automic-infra:pck.automic_chef-1.0.0

- pck.automic_mssql.index
pck.automic_mssql-1.0.0 is here. Please merge!
> automic-infra:pck.automic_mssql-1.0.0

- pck.automic_git.index
pck.automic_git-1.0.0 is here. Please merge!
> automic-infra:pck.automic_git-1.0.0

- pck.automic_cvs.index
pck.automic_cvs-1.2.0 is here. Please merge!
> automic-infra:pck.automic_cvs-1.2.0

- pck.automic_mssql.index
pck.automic_mssql-1.0.1 is here. Please merge!
> automic-infra:pck.automic_mssql-1.0.1

- pck.automic_puppet.index
pck.automic_puppet-1.0.0 is here. Please merge!
> automic-infra:pck.automic_puppet-1.0.0

- pck.automic_oracle_db.index
pck.automic_oracle_db-1.0.0 is here. Please merge!
> automic-infra:pck.automic_oracle_db-1.0.0

- pck.automic_jboss_v5.index
pck.automic_jboss_v5-1.0.0 is here. Please merge!
> automic-infra:pck.automic_jboss_v5-1.0.0

- pck.automic_dm.index
pck.automic_dm-1.1.0 is here. Please merge!
> automic-infra:pck.automic_dm-1.1.0

- pck.automic_jboss_v5.index
pck.automic_jboss_v5-1.0.1 is here. Please merge!
> automic-infra:pck.automic_jboss_v5-1.0.1

- pck.automic_amazon.index
pck.automic_amazon-1.0.0 is here. Please merge!
> automic-infra:pck.automic_amazon-1.0.0

- pck.automic_windows_registry.index
pck.automic_windows_registry-1.2.0 is here. Please merge!
> automic-infra:pck.automic_windows_registry-1.2.0

- pck.automic_dimensions.index
pck.automic_dimensions-1.0.0 is here. Please merge!
> automic-infra:pck.automic_dimensions-1.0.0

- pck.automic_weblogic.index
pck.automic_weblogic-1.1.0 is here. Please merge!
> automic-infra:pck.automic_weblogic-1.1.0

- pck.automic_dm.index
pck.automic_dm-1.2.0 is here. Please merge!
> automic-infra:pck.automic_dm-1.2.0

- pck.automic_cloudfoundry.index
pck.automic_cloudfoundry-1.0.0 is here. Please merge!
> automic-infra:pck.automic_cloudfoundry-1.0.0

- pck.automic_nexus.index
pck.automic_nexus-1.0.0 is here. Please merge!
> automic-infra:pck.automic_nexus-1.0.0

- pck.automic_jenkins.index
pck.automic_jenkins-1.1.0 is here. Please merge!
> automic-infra:pck.automic_jenkins-1.1.0

- pck.automic_siebel.index
pck.automic_siebel-3.0.1 is here. Please merge!
> automic-infra:pck.automic_siebel-3.0.1

- pck.automic_tfs.index
pck.automic_tfs-1.2.0 is here. Please merge!
> automic-infra:pck.automic_tfs-1.2.0

- pck.automic_ibm_websphere.index
pck.automic_ibm_websphere-1.1.0 is here. Please merge!
> automic-infra:pck.automic_ibm_websphere-1.1.0

- pck.automic_jenkins.index
pck.automic_jenkins-1.1.1 is here. Please merge!
> automic-infra:pck.automic_jenkins-1.1.1

- pck.automic_artifactory.index
pck.automic_artifactory-1.0.0 is here. Please merge!
> automic-infra:pck.automic_artifactory-1.0.0

- pck.automic_clearcase.index
pck.automic_clearcase-1.0.0 is here. Please merge!
> automic-infra:pck.automic_clearcase-1.0.0

- pck.itpa_shared.index
pck.itpa_shared-1.1.1 is here. Please merge!
> automic-infra:pck.itpa_shared-1.1.1

- pck.automic_vmware_vsphere.index
pck.automic_vmware_vsphere-1.0.0 is here. Please merge!
> automic-infra:pck.automic_vmware_vsphere-1.0.0

- pck.automic_oracle_soa.index
pck.automic_oracle_soa-1.0.0 is here. Please merge!
> automic-infra:pck.automic_oracle_soa-1.0.0

- pck.automic_tomcat.index
pck.automic_tomcat-1.1.0 is here. Please merge!
> automic-infra:pck.automic_tomcat-1.1.0

- pck.automic_eclipse_hudson.index
pck.automic_eclipse_hudson-1.0.0 is here. Please merge!
> automic-infra:pck.automic_eclipse_hudson-1.0.0

- pck.automic_jetbrains_teamcity.index
pck.automic_jetbrains_teamcity-1.0.0 is here. Please merge!
> automic-infra:pck.automic_jetbrains_teamcity-1.0.0

- pck.automic_oracle_soa.index
pck.automic_oracle_soa-1.0.1 is here. Please merge!
> automic-infra:pck.automic_oracle_soa-1.0.1

- pck.automic_email.index
pck.automic_email-1.1.1 is here. Please merge!
> automic-infra:pck.automic_email-1.1.1

- pck.automic_puppet.index
pck.automic_puppet-1.0.1 is here. Please merge!
> automic-infra:pck.automic_puppet-1.0.1

- pck.automic_iis.index
pck.automic_iis-1.1.0 is here. Please merge!
> automic-infra:pck.automic_iis-1.1.0

- pck.automic_bond.index
pck.automic_bond-1.0.1 is here. Please merge!
> automic-infra:pck.automic_bond-1.0.1

- pck.automic_git.index
pck.automic_git-1.0.1 is here. Please merge!
> automic-infra:pck.automic_git-1.0.1

- pck.automic_oracle_osb.index
pck.automic_oracle_osb-1.0.0 is here. Please merge!
> automic-infra:pck.automic_oracle_osb-1.0.0

- pck.automic_weblogic.index
pck.automic_weblogic-1.2.0 is here. Please merge!
> automic-infra:pck.automic_weblogic-1.2.0

- pck.automic_nexus.index
pck.automic_nexus-1.1.0 is here. Please merge!
> automic-infra:pck.automic_nexus-1.1.0

- pck.automic_artifactory.index
pck.automic_artifactory-1.1.0 is here. Please merge!
> automic-infra:pck.automic_artifactory-1.1.0

- pck.automic_docker.index
pck.automic_docker-1.3.0 is here. Please merge!
> automic-infra:pck.automic_docker-1.3.0

- pck.automic_openstack.index
pck.automic_openstack-1.1.0 is here. Please merge!
> automic-infra:pck.automic_openstack-1.1.0

- pck.automic_svn.index
pck.automic_svn-1.1.1 is here. Please merge!
> automic-infra:pck.automic_svn-1.1.1

- pck.itpa_shared.index
pck.itpa_shared-1.1.2 is here. Please merge!
> automic-infra:pck.itpa_shared-1.1.2

- pck.automic_jdbc.index
pck.automic_jdbc-1.2.0 is here. Please merge!
> automic-infra:pck.automic_jdbc-1.2.0

- pck.automic_bond.index
pck.automic_bond-1.0.2 is here. Please merge!
> automic-infra:pck.automic_bond-1.0.2

- pck.automic_dm.index
pck.automic_dm-1.2.1 is here. Please merge!
> automic-infra:pck.automic_dm-1.2.1

- pck.automic_filesystem.index
pck.automic_filesystem-1.1.1 is here. Please merge!
> automic-infra:pck.automic_filesystem-1.1.1

- pck.automic_iis.index
pck.automic_iis-1.2.0 is here. Please merge!
> automic-infra:pck.automic_iis-1.2.0

- pck.automic_cloudfoundry.index
pck.automic_cloudfoundry-1.1.0 is here. Please merge!
> automic-infra:pck.automic_cloudfoundry-1.1.0

- pck.automic_oracle_osb.index
pck.automic_oracle_osb-1.0.1 is here. Please merge!
> automic-infra:pck.automic_oracle_osb-1.0.1

- pck.automic_informatica_powercenter.index
pck.automic_informatica_powercenter-1.0.0 is here. Please merge!
> automic-infra:pck.automic_informatica_powercenter-1.0.0

- pck.automic_informatica_powercenter.index
pck.automic_informatica_powercenter-1.0.1 is here. Please merge!
> automic-infra:pck.automic_informatica_powercenter-1.0.1

- pck.automic_agent_2_agent.index
pck.automic_agent_2_agent-1.1.1 is here. Please merge!
> automic-infra:pck.automic_agent_2_agent-1.1.1

- pck.automic_bond.index
pck.automic_bond-1.0.3 is here. Please merge!
> automic-infra:pck.automic_bond-1.0.3

- pck.itpa_shared.index
pck.itpa_shared-1.2.0 is here. Please merge!
> automic-infra:pck.itpa_shared-1.2.0

- pck.automic_text.index
pck.automic_text-1.1.1 is here. Please merge!
> automic-infra:pck.automic_text-1.1.1

- pck.automic_selenium.index
PCK.AUTOMIC_SELENIUM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SELENIUM-1.0.0

- pck.automic_ibm_websphere.index
pck.automic_ibm_websphere-1.2.0 is here. Please merge!
> automic-infra:pck.automic_ibm_websphere-1.2.0

- pck.itpa_shared.index
pck.itpa_shared-1.2.1 is here. Please merge!
> automic-infra:pck.itpa_shared-1.2.1

- pck.automic_provisioning.index
pck.automic_provisioning-1.0.0 is here. Please merge!
> automic-infra:pck.automic_provisioning-1.0.0

- pck.automic_provisioning.docker.index
pck.automic_provisioning.docker-1.0.0 is here. Please merge!
> automic-infra:pck.automic_provisioning.docker-1.0.0

- pck.automic_analytics.index
pck.automic_analytics-1.0.0 is here. Please merge!
> automic-infra:pck.automic_analytics-1.0.0

- pck.automic_tmpl_ibm_websphere.index
pck.automic_tmpl_ibm_websphere-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_ibm_websphere-1.0.0

- pck.automic_tmpl_iis.index
pck.automic_tmpl_iis-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_iis-1.0.0

- pck.automic_tmpl_mssql.index
pck.automic_tmpl_mssql-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_mssql-1.0.0

- pck.automic_tmpl_oracledb.index
pck.automic_tmpl_oracledb-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_oracledb-1.0.0

- pck.automic_tmpl_jboss_v6.index
pck.automic_tmpl_jboss_v6-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_jboss_v6-1.0.0

- pck.automic_tmpl_jdbc.index
pck.automic_tmpl_jdbc-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_jdbc-1.0.0

- pck.automic_tmpl_weblogic.index
pck.automic_tmpl_weblogic-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_weblogic-1.0.0

- pck.automic_tmpl_tomcat.index
pck.automic_tmpl_tomcat-1.0.0 is here. Please merge!
> automic-infra:pck.automic_tmpl_tomcat-1.0.0

- pck.automic_analytics.index
pck.automic_analytics-1.0.1 is here. Please merge!
> automic-infra:pck.automic_analytics-1.0.1

- pck.automic_ra_rest.index
pck.automic_ra_rest-1.0.0 is here. Please merge!
> automic-infra:pck.automic_ra_rest-1.0.0

- pck.automic_cau_agent_windows.index
pck.automic_cau_agent_windows-12.0.0 is here. Please merge!
> automic-infra:pck.automic_cau_agent_windows-12.0.0

- pck.automic_cau_agent_unix.index
pck.automic_cau_agent_unix-12.0.0 is here. Please merge!
> automic-infra:pck.automic_cau_agent_unix-12.0.0

- pck.automic_agent_2_agent.index
pck.automic_agent_2_agent-1.1.2 is here. Please merge!
> automic-infra:pck.automic_agent_2_agent-1.1.2

- pck.automic_connectivity.index
pck.automic_connectivity-1.0.1 is here. Please merge!
> automic-infra:pck.automic_connectivity-1.0.1

- pck.automic_dm.index
pck.automic_dm-1.2.2 is here. Please merge!
> automic-infra:pck.automic_dm-1.2.2

- pck.automic_filesystem.index
pck.automic_filesystem-1.1.2 is here. Please merge!
> automic-infra:pck.automic_filesystem-1.1.2

- pck.automic_ftp.index
pck.automic_ftp-1.1.1 is here. Please merge!
> automic-infra:pck.automic_ftp-1.1.1

- pck.automic_http.index
pck.automic_http-1.1.1 is here. Please merge!
> automic-infra:pck.automic_http-1.1.1

- pck.automic_ini.index
pck.automic_ini-1.1.1 is here. Please merge!
> automic-infra:pck.automic_ini-1.1.1

- pck.automic_java_properties.index
pck.automic_java_properties-1.1.1 is here. Please merge!
> automic-infra:pck.automic_java_properties-1.1.1

- pck.automic_jdbc.index
pck.automic_jdbc-1.2.1 is here. Please merge!
> automic-infra:pck.automic_jdbc-1.2.1

- pck.automic_ldap.index
pck.automic_ldap-1.0.1 is here. Please merge!
> automic-infra:pck.automic_ldap-1.0.1

- pck.automic_log.index
pck.automic_log-1.0.1 is here. Please merge!
> automic-infra:pck.automic_log-1.0.1

- pck.automic_mssql.index
pck.automic_mssql-1.0.2 is here. Please merge!
> automic-infra:pck.automic_mssql-1.0.2

- pck.automic_scp.index
pck.automic_scp-1.1.1 is here. Please merge!
> automic-infra:pck.automic_scp-1.1.1

- pck.automic_sftp.index
pck.automic_sftp-1.1.1 is here. Please merge!
> automic-infra:pck.automic_sftp-1.1.1

- pck.automic_smb.index
pck.automic_smb-1.1.1 is here. Please merge!
> automic-infra:pck.automic_smb-1.1.1

- pck.automic_smoke_web.index
pck.automic_smoke_web-1.0.1 is here. Please merge!
> automic-infra:pck.automic_smoke_web-1.0.1

- pck.automic_text.index
pck.automic_text-1.1.2 is here. Please merge!
> automic-infra:pck.automic_text-1.1.2

- pck.automic_unix.index
pck.automic_unix-1.1.1 is here. Please merge!
> automic-infra:pck.automic_unix-1.1.1

- pck.automic_windows.index
pck.automic_windows-1.1.1 is here. Please merge!
> automic-infra:pck.automic_windows-1.1.1

- pck.automic_windows_service.index
pck.automic_windows_service-1.2.0 is here. Please merge!
> automic-infra:pck.automic_windows_service-1.2.0

- pck.automic_xml.index
pck.automic_xml-1.1.1 is here. Please merge!
> automic-infra:pck.automic_xml-1.1.1

- pck.automic_email.index
pck.automic_email-1.1.2 is here. Please merge!
> automic-infra:pck.automic_email-1.1.2

- pck.automic_oracle_db.index
pck.automic_oracle_db-1.0.1 is here. Please merge!
> automic-infra:pck.automic_oracle_db-1.0.1

- pck.automic_tomcat.index
pck.automic_tomcat-1.1.1 is here. Please merge!
> automic-infra:pck.automic_tomcat-1.1.1

- pck.automic_jenkins.index
pck.automic_jenkins-1.1.2 is here. Please merge!
> automic-infra:pck.automic_jenkins-1.1.2

- pck.automic_puppet_puppet.index
pck.automic_puppet_puppet-1.0.0 is here. Please merge!
> automic-infra:pck.automic_puppet_puppet-1.0.0

- pck.automic_docker.index
pck.automic_docker-1.3.1 is here. Please merge!
> automic-infra:pck.automic_docker-1.3.1

- pck.automic_puppet_puppet.index
pck.automic_puppet_puppet-1.1.0 is here. Please merge!
> automic-infra:pck.automic_puppet_puppet-1.1.0

- pck.automic_clearcase.index
pck.automic_clearcase-1.0.1 is here. Please merge!
> automic-infra:pck.automic_clearcase-1.0.1

- pck.automic_cvs.index
pck.automic_cvs-1.2.1 is here. Please merge!
> automic-infra:pck.automic_cvs-1.2.1

- pck.automic_dimensions.index
pck.automic_dimensions-1.0.1 is here. Please merge!
> automic-infra:pck.automic_dimensions-1.0.1

- pck.automic_tfs.index
pck.automic_tfs-1.2.1 is here. Please merge!
> automic-infra:pck.automic_tfs-1.2.1

- pck.automic_apache_httpserver.index
pck.automic_apache_httpserver-1.0.0 is here. Please merge!
> automic-infra:pck.automic_apache_httpserver-1.0.0

- pck.automic_provisioning.docker.index
pck.automic_provisioning.docker-1.0.1 is here. Please merge!
> automic-infra:pck.automic_provisioning.docker-1.0.1

- pck.automic_provisioning.index
pck.automic_provisioning-1.0.1 is here. Please merge!
> automic-infra:pck.automic_provisioning-1.0.1

- pck.automic_oracle_soa.index
pck.automic_oracle_soa-1.0.2 is here. Please merge!
> automic-infra:pck.automic_oracle_soa-1.0.2

- pck.automic_weblogic.index
pck.automic_weblogic-1.2.1 is here. Please merge!
> automic-infra:pck.automic_weblogic-1.2.1

- pck.automic_chef.index
pck.automic_chef-1.0.1 is here. Please merge!
> automic-infra:pck.automic_chef-1.0.1

- pck.automic_deb.index
pck.automic_deb-1.0.1 is here. Please merge!
> automic-infra:pck.automic_deb-1.0.1

- pck.automic_windows_registry.index
pck.automic_windows_registry-1.2.1 is here. Please merge!
> automic-infra:pck.automic_windows_registry-1.2.1

- pck.automic_aix.index
pck.automic_aix-1.0.1 is here. Please merge!
> automic-infra:pck.automic_aix-1.0.1

- pck.automic_f5_bigip.index
pck.automic_f5_bigip-1.0.1 is here. Please merge!
> automic-infra:pck.automic_f5_bigip-1.0.1

- pck.automic_git.index
pck.automic_git-1.0.2 is here. Please merge!
> automic-infra:pck.automic_git-1.0.2

- pck.automic_hpux.index
pck.automic_hpux-1.0.1 is here. Please merge!
> automic-infra:pck.automic_hpux-1.0.1

- pck.automic_msi.index
pck.automic_msi-1.0.1 is here. Please merge!
> automic-infra:pck.automic_msi-1.0.1

- pck.automic_rpm.index
pck.automic_rpm-1.0.1 is here. Please merge!
> automic-infra:pck.automic_rpm-1.0.1

- pck.automic_puppet.index
pck.automic_puppet-1.0.2 is here. Please merge!
> automic-infra:pck.automic_puppet-1.0.2

- pck.automic_jenkins.index
pck.automic_jenkins-1.1.3 is here. Please merge!
> automic-infra:pck.automic_jenkins-1.1.3

- pck.automic_iis.index
pck.automic_iis-1.2.1 is here. Please merge!
> automic-infra:pck.automic_iis-1.2.1

- pck.automic_bond.index
pck.automic_bond-1.0.4 is here. Please merge!
> automic-infra:pck.automic_bond-1.0.4

- pck.automic_ibm_websphere.index
pck.automic_ibm_websphere-1.2.1 is here. Please merge!
> automic-infra:pck.automic_ibm_websphere-1.2.1

- pck.automic_jboss_v6.index
pck.automic_jboss_v6-1.0.1 is here. Please merge!
> automic-infra:pck.automic_jboss_v6-1.0.1

- pck.automic_jboss_v5.index
pck.automic_jboss_v5-1.0.2 is here. Please merge!
> automic-infra:pck.automic_jboss_v5-1.0.2

- pck.automic_msi.index
pck.automic_msi-1.0.2 is here. Please merge!
> automic-infra:pck.automic_msi-1.0.2

- pck.automic_iis.index
pck.automic_iis-1.2.2 is here. Please merge!
> automic-infra:pck.automic_iis-1.2.2

- pck.automic_siebel.index
pck.automic_siebel-4.0.0 is here. Please merge!
> automic-infra:pck.automic_siebel-4.0.0

- pck.automic_jdbc.index
pck.automic_jdbc-1.2.2 is here. Please merge!
> automic-infra:pck.automic_jdbc-1.2.2

- pck.automic_filesystem.index
pck.automic_filesystem-1.1.3 is here. Please merge!
> automic-infra:pck.automic_filesystem-1.1.3

- pck.automic_puppet_puppet.index
pck.automic_puppet_puppet-1.1.1 is here. Please merge!
> automic-infra:pck.automic_puppet_puppet-1.1.1

- pck.automic_jenkins.index
pck.automic_jenkins-1.1.4 is here. Please merge!
> automic-infra:pck.automic_jenkins-1.1.4

- pck.automic_scp.index
pck.automic_scp-1.1.2 is here. Please merge!
> automic-infra:pck.automic_scp-1.1.2

- pck.automic_ftp.index
pck.automic_ftp-1.1.2 is here. Please merge!
> automic-infra:pck.automic_ftp-1.1.2

- pck.automic_http.index
pck.automic_http-1.1.2 is here. Please merge!
> automic-infra:pck.automic_http-1.1.2

- pck.automic_sftp.index
pck.automic_sftp-1.1.2 is here. Please merge!
> automic-infra:pck.automic_sftp-1.1.2

- pck.automic_smb.index
pck.automic_smb-1.1.2 is here. Please merge!
> automic-infra:pck.automic_smb-1.1.2

- pck.automic_filesystem.index
pck.automic_filesystem-1.2.0 is here. Please merge!
> automic-infra:pck.automic_filesystem-1.2.0

- pck.automic_ldap.index
pck.automic_ldap-1.0.2 is here. Please merge!
> automic-infra:pck.automic_ldap-1.0.2

- pck.automic_jboss_v6.index
pck.automic_jboss_v6-1.0.2 is here. Please merge!
> automic-infra:pck.automic_jboss_v6-1.0.2

- pck.automic_vmware_vsphere.index
pck.automic_vmware_vsphere-1.1.0 is here. Please merge!
> automic-infra:pck.automic_vmware_vsphere-1.1.0

- pck.automic_puppet_puppet.index
pck.automic_puppet_puppet-1.2.0 is here. Please merge!
> automic-infra:pck.automic_puppet_puppet-1.2.0

- pck.automic_cau_agent_windows.index
pck.automic_cau_agent_windows-12.0.1 is here. Please merge!
> automic-infra:pck.automic_cau_agent_windows-12.0.1

- pck.automic_cau_agent_unix.index
pck.automic_cau_agent_unix-12.0.1 is here. Please merge!
> automic-infra:pck.automic_cau_agent_unix-12.0.1

- pck.automic_jdbc.index
pck.automic_jdbc-1.2.3 is here. Please merge!
> automic-infra:pck.automic_jdbc-1.2.3

- pck.itpa_shared.index
pck.itpa_shared-1.2.2 is here. Please merge!
> automic-infra:pck.itpa_shared-1.2.2

- PCK.AUTOMIC_JDBC.index
PCK.AUTOMIC_JDBC-1.2.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JDBC-1.2.4

- PCK.AUTOMIC_ATLASSIAN_JIRA.index
PCK.AUTOMIC_ATLASSIAN_JIRA-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_ATLASSIAN_JIRA-1.0.0

- PCK.AUTOMIC_SCVMM.index
PCK.AUTOMIC_SCVMM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SCVMM-1.0.0

- PCK.AUTOMIC_CA_BLAZEMETER.index
PCK.AUTOMIC_CA_BLAZEMETER-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_BLAZEMETER-1.0.0

- PCK.AUTOMIC_CA_TDM.index
PCK.AUTOMIC_CA_TDM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_TDM-1.0.0

- PCK.AUTOMIC_XML.index
PCK.AUTOMIC_XML-1.1.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_XML-1.1.2

- PCK.AUTOMIC_CA_SV.index
PCK.AUTOMIC_CA_SV-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_SV-1.0.0

- PCK.AUTOMIC_SCVMM.index
PCK.AUTOMIC_SCVMM-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SCVMM-1.1.0

- PCK.AUTOMIC_VMWARE_VSPHERE.index
PCK.AUTOMIC_VMWARE_VSPHERE-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_VMWARE_VSPHERE-1.1.1

- PCK.AUTOMIC_CA_AGILECENTRAL.index
PCK.AUTOMIC_CA_AGILECENTRAL-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_AGILECENTRAL-1.0.0

- PCK.AUTOMIC_CA_SDM.index
PCK.AUTOMIC_CA_SDM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_SDM-1.0.0

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.0.2

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.2.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.2.3

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.1

- PCK.AUTOMIC_FTP.index
PCK.AUTOMIC_FTP-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FTP-1.1.3

- PCK.AUTOMIC_HTTP.index
PCK.AUTOMIC_HTTP-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_HTTP-1.1.3

- PCK.AUTOMIC_WINDOWS_SERVICE.index
PCK.AUTOMIC_WINDOWS_SERVICE-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_WINDOWS_SERVICE-1.2.1

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.3.0

- PCK.AUTOMIC_SMB.index
PCK.AUTOMIC_SMB-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SMB-1.1.3

- PCK.AUTOMIC_INI.index
PCK.AUTOMIC_INI-1.1.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INI-1.1.2

- PCK.AUTOMIC_AMAZON.index
PCK.AUTOMIC_AMAZON-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AMAZON-1.0.1

- PCK.AUTOMIC_SOLARIS.index
PCK.AUTOMIC_SOLARIS-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SOLARIS-1.0.1

- PCK.ITPA_SHARED.index
PCK.ITPA_SHARED-1.2.3 is here. Please merge!
> automic-infra:PCK.ITPA_SHARED-1.2.3

- PCK.AUTOMIC_ORACLE_DB.index
PCK.AUTOMIC_ORACLE_DB-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_ORACLE_DB-1.0.2

- PCK.AUTOMIC_TEMENOS_T24.index
PCK.AUTOMIC_TEMENOS_T24-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEMENOS_T24-1.0.0

- PCK.AUTOMIC_VMWARE_VSPHERE.index
PCK.AUTOMIC_VMWARE_VSPHERE-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_VMWARE_VSPHERE-1.2.0

- PCK.AUTOMIC_AMAZON.index
PCK.AUTOMIC_AMAZON-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AMAZON-1.1.0

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.0.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.0.3

- PCK.AUTOMIC_CAU_AGENT_WINDOWS.index
PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.0.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.0.3

- PCK.AUTOMIC_INI.index
PCK.AUTOMIC_INI-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INI-1.1.3

- PCK.ITPA_SHARED.index
PCK.ITPA_SHARED-1.2.4 is here. Please merge!
> automic-infra:PCK.ITPA_SHARED-1.2.4

- PCK.AUTOMIC_TEXT.index
PCK.AUTOMIC_TEXT-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEXT-1.1.3

- PCK.AUTOMIC_AMAZON.index
PCK.AUTOMIC_AMAZON-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AMAZON-1.1.1

- PCK.AUTOMIC_AGENT_DEPLOYMENT.index
PCK.AUTOMIC_AGENT_DEPLOYMENT-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AGENT_DEPLOYMENT-1.0.0

- PCK.AUTOMIC_PROVISIONING.AWS.index
PCK.AUTOMIC_PROVISIONING.AWS-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING.AWS-1.0.0

- PCK.AUTOMIC_PROVISIONING.index
PCK.AUTOMIC_PROVISIONING-2.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING-2.0.0

- PCK.AUTOMIC_PROVISIONING.DOCKER.index
PCK.AUTOMIC_PROVISIONING.DOCKER-2.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING.DOCKER-2.0.0

- PCK.AUTOMIC_PROVISIONING.VMWARE.index
PCK.AUTOMIC_PROVISIONING.VMWARE-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING.VMWARE-1.0.0

- PCK.AUTOMIC_BOND.index
PCK.AUTOMIC_BOND-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_BOND-1.1.0

- PCK.AUTOMIC_CYCK_UPGRADE_CHECKER.index
PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.0

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.1.0

- PCK.AUTOMIC_CAU_AGENT_WINDOWS.index
PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.1.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.2

- PCK.AUTOMIC_JDBC.index
PCK.AUTOMIC_JDBC-1.2.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JDBC-1.2.5

- PCK.AUTOMIC_PROVISIONING.VMWARE.index
PCK.AUTOMIC_PROVISIONING.VMWARE-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING.VMWARE-1.0.1

- PCK.AUTOMIC_PROVISIONING.AWS.index
PCK.AUTOMIC_PROVISIONING.AWS-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING.AWS-1.0.1

- PCK.AUTOMIC_PROVISIONING.DOCKER.index
PCK.AUTOMIC_PROVISIONING.DOCKER-2.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_PROVISIONING.DOCKER-2.0.1

- PCK.AUTOMIC_IBM_ZOS.index
PCK.AUTOMIC_IBM_ZOS-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_ZOS-1.3.0

- PCK.AUTOMIC_TEMENOS_T24.index
PCK.AUTOMIC_TEMENOS_T24-2.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEMENOS_T24-2.0.0

- PCK.AUTOMIC_TEMENOS_T24_CD.index
PCK.AUTOMIC_TEMENOS_T24_CD-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEMENOS_T24_CD-1.0.0

- PCK.AUTOMIC_IIS.index
PCK.AUTOMIC_IIS-1.2.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IIS-1.2.3

- PCK.AUTOMIC_EXCEL.index
PCK.AUTOMIC_EXCEL-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_EXCEL-1.1.0

- PCK.AUTOMIC_RULE_SIMPLE.index
PCK.AUTOMIC_RULE_SIMPLE-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_SIMPLE-1.0.1

- PCK.AUTOMIC_RULE_STATECHANGE.index
PCK.AUTOMIC_RULE_STATECHANGE-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_STATECHANGE-1.0.0

- PCK.AUTOMIC_RM.index
PCK.AUTOMIC_RM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RM-1.0.0

- PCK.AUTOMIC_KVM.index
PCK.AUTOMIC_KVM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_KVM-1.0.0

- PCK.AUTOMIC_EMAIL.index
PCK.AUTOMIC_EMAIL-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_EMAIL-1.1.3

- PCK.AUTOMIC_SMB.index
PCK.AUTOMIC_SMB-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SMB-1.1.4

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.2.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.2.4

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.3

- PCK.AUTOMIC_KUBERNETES.index
PCK.AUTOMIC_KUBERNETES-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_KUBERNETES-1.0.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.4

- PCK.AUTOMIC_TMPL_JBOSS_V7.index
PCK.AUTOMIC_TMPL_JBOSS_V7-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_JBOSS_V7-1.0.0

- PCK.AUTOMIC_GIT.index
PCK.AUTOMIC_GIT-1.0.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_GIT-1.0.3

- PCK.AUTOMIC_MICROSOFT_BIZTALK.index
PCK.AUTOMIC_MICROSOFT_BIZTALK-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_MICROSOFT_BIZTALK-1.0.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.5

- PCK.AUTOMIC_HTTP.index
PCK.AUTOMIC_HTTP-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_HTTP-1.1.4

- PCK.ITPA_SHARED.index
PCK.ITPA_SHARED-1.2.5 is here. Please merge!
> automic-infra:PCK.ITPA_SHARED-1.2.5

- PCK.AUTOMIC_TEXT.index
PCK.AUTOMIC_TEXT-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEXT-1.1.4

- PCK.AUTOMIC_CA_APM.index
PCK.AUTOMIC_CA_APM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_APM-1.0.0

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.0.0

- PCK.AUTOMIC_EMAIL.index
PCK.AUTOMIC_EMAIL-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_EMAIL-1.1.4

- PCK.AUTOMIC_CA_AUTOSYS.index
PCK.AUTOMIC_CA_AUTOSYS-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_AUTOSYS-1.0.0

- PCK.AUTOMIC_JENKINS.index
PCK.AUTOMIC_JENKINS-1.1.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JENKINS-1.1.5

- PCK.AUTOMIC_NEXUS_V3.index
PCK.AUTOMIC_NEXUS_V3-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_NEXUS_V3-1.0.0

- PCK.AUTOMIC_MICROSOFT_WINRM.index
PCK.AUTOMIC_MICROSOFT_WINRM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_MICROSOFT_WINRM-1.0.0

- PCK.AUTOMIC_GIT.index
PCK.AUTOMIC_GIT-1.0.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_GIT-1.0.4

- PCK.AUTOMIC_BOND.index
PCK.AUTOMIC_BOND-1.1.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_BOND-1.1.2

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.2.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.2.5

- PCK.AUTOMIC_CA_HARVEST.index
PCK.AUTOMIC_CA_HARVEST-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_HARVEST-1.0.0

- PCK.AUTOMIC_RULE_STATECHANGE.index
PCK.AUTOMIC_RULE_STATECHANGE-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_STATECHANGE-1.1.0

- PCK.AUTOMIC_IIS.index
PCK.AUTOMIC_IIS-1.2.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IIS-1.2.4

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.7 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.7

- PCK.AUTOMIC_JDBC.index
PCK.AUTOMIC_JDBC-1.2.6 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JDBC-1.2.6

- PCK.AUTOMIC_MSSQL.index
PCK.AUTOMIC_MSSQL-1.0.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_MSSQL-1.0.3

- PCK.AUTOMIC_SCP.index
PCK.AUTOMIC_SCP-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SCP-1.1.3

- PCK.AUTOMIC_TEXT.index
PCK.AUTOMIC_TEXT-1.1.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEXT-1.1.5

- PCK.AUTOMIC_WINDOWS.index
PCK.AUTOMIC_WINDOWS-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_WINDOWS-1.1.3

- PCK.AUTOMIC_INI.index
PCK.AUTOMIC_INI-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INI-1.1.4

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.0.0

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.2.6 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.2.6

- PCK.AUTOMIC_AGENT_DEPLOYMENT.index
PCK.AUTOMIC_AGENT_DEPLOYMENT-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AGENT_DEPLOYMENT-1.1.0

- PCK.AUTOMIC_BOND.index
PCK.AUTOMIC_BOND-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_BOND-1.2.0

- PCK.AUTOMIC_HTTP.index
PCK.AUTOMIC_HTTP-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_HTTP-1.2.0

- PCK.AUTOMIC_TOMCAT.index
PCK.AUTOMIC_TOMCAT-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TOMCAT-1.2.0

- PCK.AUTOMIC_SMB.index
PCK.AUTOMIC_SMB-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SMB-1.2.0

- PCK.AUTOMIC_FTP.index
PCK.AUTOMIC_FTP-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FTP-1.2.0

- PCK.AUTOMIC_JDBC.index
PCK.AUTOMIC_JDBC-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JDBC-1.3.0

- PCK.AUTOMIC_CA_CA7.index
PCK.AUTOMIC_CA_CA7-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_CA7-1.0.0

- PCK.AUTOMIC_CA_ESP.index
PCK.AUTOMIC_CA_ESP-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_ESP-1.0.0

- PCK.AUTOMIC_WEBLOGIC.index
PCK.AUTOMIC_WEBLOGIC-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_WEBLOGIC-1.3.0

- PCK.AUTOMIC_FTP.index
PCK.AUTOMIC_FTP-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FTP-1.2.1

- PCK.AUTOMIC_NEXUS_V3.index
PCK.AUTOMIC_NEXUS_V3-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_NEXUS_V3-1.1.0

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.4.0

- PCK.AUTOMIC_SCP.index
PCK.AUTOMIC_SCP-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SCP-1.2.0

- PCK.AUTOMIC_GIT.index
PCK.AUTOMIC_GIT-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_GIT-1.1.0

- PCK.AUTOMIC_XML.index
PCK.AUTOMIC_XML-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_XML-1.2.0

- PCK.AUTOMIC_JENKINS.index
PCK.AUTOMIC_JENKINS-1.1.6 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JENKINS-1.1.6

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.2.7 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.2.7

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.5.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.5.0

- PCK.AUTOMIC_CLOUDFOUNDRY.index
PCK.AUTOMIC_CLOUDFOUNDRY-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CLOUDFOUNDRY-1.1.1

- PCK.AUTOMIC_CA_BLAZEMETER.index
PCK.AUTOMIC_CA_BLAZEMETER-2.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_BLAZEMETER-2.0.0

- PCK.AUTOMIC_CA_ASM.index
PCK.AUTOMIC_CA_ASM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_ASM-1.0.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.2.8 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.2.8

- PCK.AUTOMIC_CA_CA7.index
PCK.AUTOMIC_CA_CA7-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_CA7-1.1.0

- PCK.AUTOMIC_CA_APIM.index
PCK.AUTOMIC_CA_APIM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_APIM-1.0.0

- PCK.AUTOMIC_ARTIFACTORY.index
PCK.AUTOMIC_ARTIFACTORY-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_ARTIFACTORY-1.2.0

- PCK.AUTOMIC_JBOSS_V7.index
PCK.AUTOMIC_JBOSS_V7-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JBOSS_V7-1.2.0

- PCK.AUTOMIC_IIS.index
PCK.AUTOMIC_IIS-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IIS-1.3.0

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.0.1

- PCK.AUTOMIC_UIPATH.index
PCK.AUTOMIC_UIPATH-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_UIPATH-1.0.0

- PCK.AUTOMIC_ARTIFACTORY.index
PCK.AUTOMIC_ARTIFACTORY-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_ARTIFACTORY-1.2.1

- PCK.AUTOMIC_CA_BLAZEMETER.index
PCK.AUTOMIC_CA_BLAZEMETER-2.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_BLAZEMETER-2.0.1

- PCK.AUTOMIC_CLOUDFOUNDRY.index
PCK.AUTOMIC_CLOUDFOUNDRY-1.1.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CLOUDFOUNDRY-1.1.2

- PCK.AUTOMIC_TEMENOS_T24.index
PCK.AUTOMIC_TEMENOS_T24-2.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEMENOS_T24-2.1.1

- PCK.AUTOMIC_OPENSTACK.index
PCK.AUTOMIC_OPENSTACK-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_OPENSTACK-1.1.1

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.0.1

- PCK.AUTOMIC_AUTOMATION_ANYWHERE.index
PCK.AUTOMIC_AUTOMATION_ANYWHERE-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AUTOMATION_ANYWHERE-1.0.0

- PCK.AUTOMIC_CAU_AGENT_WINDOWS.index
PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.2.1

- PCK.AUTOMIC_CYCK_UPGRADE_CHECKER.index
PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.3

- PCK.AUTOMIC_SVN.index
PCK.AUTOMIC_SVN-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SVN-1.2.0

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.2.1

- PCK.AUTOMIC_TFS.index
PCK.AUTOMIC_TFS-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TFS-1.3.0

- PCK.AUTOMIC_UIPATH.index
PCK.AUTOMIC_UIPATH-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_UIPATH-1.1.0

- PCK.AUTOMIC_JSON.index
PCK.AUTOMIC_JSON-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JSON-1.0.0

- PCK.AUTOMIC_SIEBEL_IP18.index
PCK.AUTOMIC_SIEBEL_IP18-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL_IP18-1.0.0

- PCK.AUTOMIC_SIEBEL_IP18.index
PCK.AUTOMIC_SIEBEL_IP18-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL_IP18-1.0.1

- PCK.AUTOMIC_APACHE_KAFKA.index
PCK.AUTOMIC_APACHE_KAFKA-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_APACHE_KAFKA-1.0.0

- PCK.AUTOMIC_SERVICENOW.index
PCK.AUTOMIC_SERVICENOW-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SERVICENOW-1.0.0

- PCK.AUTOMIC_RULE_STATECHANGE.index
PCK.AUTOMIC_RULE_STATECHANGE-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_STATECHANGE-1.2.0

- PCK.AUTOMIC_RULE_SIMPLE.index
PCK.AUTOMIC_RULE_SIMPLE-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_SIMPLE-1.2.0

- PCK.AUTOMIC_CA_PAM.index
PCK.AUTOMIC_CA_PAM-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_PAM-1.0.0

- PCK.AUTOMIC_SIEBEL_IP18.index
PCK.AUTOMIC_SIEBEL_IP18-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL_IP18-1.0.2

- PCK.AUTOMIC_WINDOWS.index
PCK.AUTOMIC_WINDOWS-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_WINDOWS-1.1.4

- PCK.AUTOMIC_RA_REST.index
PCK.AUTOMIC_RA_REST-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RA_REST-1.0.1

- PCK.AUTOMIC_NEXUS_V3.index
PCK.AUTOMIC_NEXUS_V3-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_NEXUS_V3-1.2.0

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.0.2

- PCK.AUTOMIC_HPQC.index
PCK.AUTOMIC_HPQC-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_HPQC-1.1.1

- PCK.AUTOMIC_NEXUS_V3.index
PCK.AUTOMIC_NEXUS_V3-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_NEXUS_V3-1.2.1

- PCK.AUTOMIC_SERVICENOW.index
PCK.AUTOMIC_SERVICENOW-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SERVICENOW-1.1.0

- PCK.AUTOMIC_JSON.index
PCK.AUTOMIC_JSON-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JSON-1.0.1

- PCK.AUTOMIC_CA_SERVICECATALOG.index
PCK.AUTOMIC_CA_SERVICECATALOG-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_SERVICECATALOG-1.0.0

- PCK.AUTOMIC_YAML.index
PCK.AUTOMIC_YAML-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_YAML-1.0.0

- PCK.AUTOMIC_TEXT.index
PCK.AUTOMIC_TEXT-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TEXT-1.2.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.3.0

- PCK.AUTOMIC_INI.index
PCK.AUTOMIC_INI-1.1.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INI-1.1.5

- PCK.AUTOMIC_CONNECTIVITY.index
PCK.AUTOMIC_CONNECTIVITY-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CONNECTIVITY-1.0.2

- PCK.AUTOMIC_EMAIL.index
PCK.AUTOMIC_EMAIL-1.1.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_EMAIL-1.1.5

- PCK.AUTOMIC_SMB.index
PCK.AUTOMIC_SMB-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SMB-1.2.1

- PCK.AUTOMIC_XML.index
PCK.AUTOMIC_XML-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_XML-1.2.1

- PCK.AUTOMIC_TOMCAT.index
PCK.AUTOMIC_TOMCAT-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TOMCAT-1.3.0

- PCK.AUTOMIC_IIS.index
PCK.AUTOMIC_IIS-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IIS-1.4.0

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.3.0

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.6.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.6.0

- PCK.AUTOMIC_JDBC.index
PCK.AUTOMIC_JDBC-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JDBC-1.4.0

- PCK.AUTOMIC_MSSQL.index
PCK.AUTOMIC_MSSQL-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_MSSQL-1.1.0

- PCK.AUTOMIC_RULE_STATECHANGE.index
PCK.AUTOMIC_RULE_STATECHANGE-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_STATECHANGE-1.3.0

- PCK.AUTOMIC_RULE_SIMPLE.index
PCK.AUTOMIC_RULE_SIMPLE-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_RULE_SIMPLE-1.3.0

- PCK.AUTOMIC_BOND.index
PCK.AUTOMIC_BOND-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_BOND-1.3.0

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.0

- PCK.AUTOMIC_CAU_AGENT_RA.index
PCK.AUTOMIC_CAU_AGENT_RA-12.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_RA-12.3.0

- PCK.AUTOMIC_CAU_AGENT_SQL.index
PCK.AUTOMIC_CAU_AGENT_SQL-12.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SQL-12.3.0

- PCK.AUTOMIC_TENABLE_IO.index
PCK.AUTOMIC_TENABLE_IO-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TENABLE_IO-1.0.0

- PCK.AUTOMIC_AGENT_DEPLOYMENT.index
PCK.AUTOMIC_AGENT_DEPLOYMENT-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AGENT_DEPLOYMENT-1.2.0

- PCK.AUTOMIC_HTTP.index
PCK.AUTOMIC_HTTP-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_HTTP-1.2.1

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.1.0

- PCK.AUTOMIC_TMPL_IBM_WEBSPHERE.index
PCK.AUTOMIC_TMPL_IBM_WEBSPHERE-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_IBM_WEBSPHERE-1.1.0

- PCK.AUTOMIC_TMPL_JBOSS_V7.index
PCK.AUTOMIC_TMPL_JBOSS_V7-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_JBOSS_V7-1.1.0

- PCK.AUTOMIC_TMPL_JDBC.index
PCK.AUTOMIC_TMPL_JDBC-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_JDBC-1.1.0

- PCK.AUTOMIC_TMPL_MSSQL.index
PCK.AUTOMIC_TMPL_MSSQL-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_MSSQL-1.1.0

- PCK.AUTOMIC_TMPL_ORACLEDB.index
PCK.AUTOMIC_TMPL_ORACLEDB-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_ORACLEDB-1.1.0

- PCK.AUTOMIC_TMPL_TOMCAT.index
PCK.AUTOMIC_TMPL_TOMCAT-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_TOMCAT-1.1.0

- PCK.AUTOMIC_TMPL_WEBLOGIC.index
PCK.AUTOMIC_TMPL_WEBLOGIC-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TMPL_WEBLOGIC-1.1.0

- PCK.AUTOMIC_EMAIL.index
PCK.AUTOMIC_EMAIL-1.1.6 is here. Please merge!
> automic-infra:PCK.AUTOMIC_EMAIL-1.1.6

- PCK.AUTOMIC_BROCADE.index
PCK.AUTOMIC_BROCADE-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_BROCADE-1.0.0

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.1.1

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.0.2

- PCK.AUTOMIC_SIEBEL_IP18.index
PCK.AUTOMIC_SIEBEL_IP18-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL_IP18-1.1.0

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.1.0

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.2.0

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.3.0

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.4.0

- PCK.AUTOMIC_SONIC.index
PCK.AUTOMIC_SONIC-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SONIC-1.0.0

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.4.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.4.1

- PCK.AUTOMIC_INI.index
PCK.AUTOMIC_INI-1.1.6 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INI-1.1.6

- PCK.AUTOMIC_CONNECTIVITY.index
PCK.AUTOMIC_CONNECTIVITY-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CONNECTIVITY-1.1.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.4.0

- PCK.ITPA_SHARED.index
PCK.ITPA_SHARED-1.3.0 is here. Please merge!
> automic-infra:PCK.ITPA_SHARED-1.3.0

- PCK.AUTOMIC_JAVA.index
PCK.AUTOMIC_JAVA-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JAVA-1.0.0

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.7.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.7.0

- PCK.AUTOMIC_JBOSS_V7.index
PCK.AUTOMIC_JBOSS_V7-1.3.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JBOSS_V7-1.3.0

- PCK.AUTOMIC_AIOPS_SHARED.index
PCK.AUTOMIC_AIOPS_SHARED-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AIOPS_SHARED-1.0.0

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.5.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.5.0

- PCK.AUTOMIC_JAVA.index
PCK.AUTOMIC_JAVA-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JAVA-1.0.1

- PCK.AUTOMIC_OPERATINGSYSTEM.index
PCK.AUTOMIC_OPERATINGSYSTEM-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_OPERATINGSYSTEM-1.0.1

- PCK.AUTOMIC_CYCK_UPGRADE_CHECKER.index
PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.4

- PCK.AUTOMIC_CYCK_UPGRADE_CHECKER.index
PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.5 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CYCK_UPGRADE_CHECKER-1.1.5

- PCK.ITPA_SHARED.index
PCK.ITPA_SHARED-1.3.1 is here. Please merge!
> automic-infra:PCK.ITPA_SHARED-1.3.1

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.2

- PCK.AUTOMIC_CAU_AGENT_WINDOWS.index
PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.3.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.3.2

- PCK.AUTOMIC_CAU_AGENT_PS.index
PCK.AUTOMIC_CAU_AGENT_PS-12.3.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_PS-12.3.2

- PCK.AUTOMIC_CAU_AGENT_RA.index
PCK.AUTOMIC_CAU_AGENT_RA-12.3.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_RA-12.3.2

- PCK.AUTOMIC_CAU_AGENT_SAP.index
PCK.AUTOMIC_CAU_AGENT_SAP-12.3.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SAP-12.3.2

- PCK.AUTOMIC_CAU_AGENT_SQL.index
PCK.AUTOMIC_CAU_AGENT_SQL-12.3.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SQL-12.3.2

- PCK.AUTOMIC_NETCONF.index
PCK.AUTOMIC_NETCONF-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_NETCONF-1.0.0

- PCK.AUTOMIC_TOMCAT.index
PCK.AUTOMIC_TOMCAT-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TOMCAT-1.4.0

- PCK.AUTOMIC_AIOPS_SHARED.index
PCK.AUTOMIC_AIOPS_SHARED-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AIOPS_SHARED-1.0.1

- PCK.AUTOMIC_SERVICENOW.index
PCK.AUTOMIC_SERVICENOW-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SERVICENOW-1.1.1

- PCK.AUTOMIC_SIEBEL.index
PCK.AUTOMIC_SIEBEL-5.6.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL-5.6.0

- PCK.AUTOMIC_INFRASTRUCTURE_MANAGER.index
PCK.AUTOMIC_INFRASTRUCTURE_MANAGER-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INFRASTRUCTURE_MANAGER-1.1.0

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.2.0

- PCK.AUTOMIC_SIEBEL_IP18.index
PCK.AUTOMIC_SIEBEL_IP18-1.2.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SIEBEL_IP18-1.2.0

- PCK.AUTOMIC_F5_BIGIP.index
PCK.AUTOMIC_F5_BIGIP-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_F5_BIGIP-1.1.0

- PCK.AUTOMIC_AIOPS_SHARED.index
PCK.AUTOMIC_AIOPS_SHARED-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AIOPS_SHARED-1.0.2

- PCK.AUTOMIC_CITRIX_NETSCALER.index
PCK.AUTOMIC_CITRIX_NETSCALER-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CITRIX_NETSCALER-1.0.0

- PCK.AUTOMIC_MICROSOFT_OFFICE365.index
PCK.AUTOMIC_MICROSOFT_OFFICE365-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_MICROSOFT_OFFICE365-1.0.0

- PCK.AUTOMIC_XML.index
PCK.AUTOMIC_XML-1.2.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_XML-1.2.3

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.8.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.8.0

- PCK.AUTOMIC_JENKINS.index
PCK.AUTOMIC_JENKINS-1.1.8 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JENKINS-1.1.8

- PCK.AUTOMIC_BOND.index
PCK.AUTOMIC_BOND-1.3.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_BOND-1.3.1

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.3

- PCK.AUTOMIC_CAU_AGENT_WINDOWS.index
PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.3.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.3.3

- PCK.AUTOMIC_CAU_AGENT_PS.index
PCK.AUTOMIC_CAU_AGENT_PS-12.3.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_PS-12.3.3

- PCK.AUTOMIC_CAU_AGENT_RA.index
PCK.AUTOMIC_CAU_AGENT_RA-12.3.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_RA-12.3.3

- PCK.AUTOMIC_CAU_AGENT_SAP.index
PCK.AUTOMIC_CAU_AGENT_SAP-12.3.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SAP-12.3.3

- PCK.AUTOMIC_CAU_AGENT_SQL.index
PCK.AUTOMIC_CAU_AGENT_SQL-12.3.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SQL-12.3.3

- PCK.AUTOMIC_HELM.index
PCK.AUTOMIC_HELM-2.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_HELM-2.0.0

- PCK.AUTOMIC_INI.index
PCK.AUTOMIC_INI-1.1.7 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INI-1.1.7

- PCK.AUTOMIC_ACRONIS.index
PCK.AUTOMIC_ACRONIS-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_ACRONIS-1.0.0

- PCK.AUTOMIC_FS.index
PCK.AUTOMIC_FS-1.0.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FS-1.0.0

- PCK.AUTOMIC_CITRIX_NETSCALER.index
PCK.AUTOMIC_CITRIX_NETSCALER-1.1.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CITRIX_NETSCALER-1.1.0

- PCK.AUTOMIC_CA_AUTOSYS.index
PCK.AUTOMIC_CA_AUTOSYS-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_AUTOSYS-1.0.1

- PCK.AUTOMIC_WEBLOGIC.index
PCK.AUTOMIC_WEBLOGIC-1.4.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_WEBLOGIC-1.4.1

- PCK.AUTOMIC_CA_ENDEVOR.index
PCK.AUTOMIC_CA_ENDEVOR-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_ENDEVOR-1.2.1

- PCK.AUTOMIC_VMWARE_VSPHERE.index
PCK.AUTOMIC_VMWARE_VSPHERE-1.2.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_VMWARE_VSPHERE-1.2.2

- PCK.AUTOMIC_IBM_WEBSPHERE.index
PCK.AUTOMIC_IBM_WEBSPHERE-1.8.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_IBM_WEBSPHERE-1.8.1

- PCK.AUTOMIC_SSH.index
PCK.AUTOMIC_SSH-1.2.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SSH-1.2.1

- PCK.AUTOMIC_INFRASTRUCTURE_MANAGER.index
PCK.AUTOMIC_INFRASTRUCTURE_MANAGER-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_INFRASTRUCTURE_MANAGER-1.1.1

- PCK.AUTOMIC_OPERATINGSYSTEM.index
PCK.AUTOMIC_OPERATINGSYSTEM-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_OPERATINGSYSTEM-1.0.2

- PCK.AUTOMIC_JAVA.index
PCK.AUTOMIC_JAVA-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JAVA-1.0.2

- PCK.AUTOMIC_JSON.index
PCK.AUTOMIC_JSON-1.0.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JSON-1.0.2

- PCK.AUTOMIC_AIOPS_SHARED.index
PCK.AUTOMIC_AIOPS_SHARED-1.0.3 is here. Please merge!
> automic-infra:PCK.AUTOMIC_AIOPS_SHARED-1.0.3

- PCK.AUTOMIC_CA_CA7.index
PCK.AUTOMIC_CA_CA7-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_CA7-1.1.1

- PCK.AUTOMIC_TOMCAT.index
PCK.AUTOMIC_TOMCAT-1.5.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_TOMCAT-1.5.0

- PCK.AUTOMIC_CA_SDM.index
PCK.AUTOMIC_CA_SDM-1.0.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CA_SDM-1.0.1

- PCK.AUTOMIC_DM.index
PCK.AUTOMIC_DM-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_DM-1.4.0

- PCK.AUTOMIC_FILESYSTEM.index
PCK.AUTOMIC_FILESYSTEM-1.4.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_FILESYSTEM-1.4.1

- PCK.AUTOMIC_JBOSS_V7.index
PCK.AUTOMIC_JBOSS_V7-1.4.0 is here. Please merge!
> automic-infra:PCK.AUTOMIC_JBOSS_V7-1.4.0

- PCK.AUTOMIC_SERVICENOW.index
PCK.AUTOMIC_SERVICENOW-1.1.2 is here. Please merge!
> automic-infra:PCK.AUTOMIC_SERVICENOW-1.1.2

- PCK.AUTOMIC_CAU_AGENT_UNIX.index
PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_UNIX-12.3.4

- PCK.AUTOMIC_CAU_AGENT_WINDOWS.index
PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.3.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_WINDOWS-12.3.4

- PCK.AUTOMIC_CAU_AGENT_SAP.index
PCK.AUTOMIC_CAU_AGENT_SAP-12.3.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SAP-12.3.4

- PCK.AUTOMIC_CAU_AGENT_SQL.index
PCK.AUTOMIC_CAU_AGENT_SQL-12.3.4 is here. Please merge!
> automic-infra:PCK.AUTOMIC_CAU_AGENT_SQL-12.3.4

- PCK.AUTOMIC_GIT.index
PCK.AUTOMIC_GIT-1.1.1 is here. Please merge!
> automic-infra:PCK.AUTOMIC_GIT-1.1.1
